### ISSUE TITLE
I got this problem 

### ISSUE THREAD

**Issue by FarzadAzima** [nats-io/nats-parent-pom#1]
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: osx-x86_64
[WARNING] Failed to inject repository session properties.
java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;
    at kr.motd.maven.os.RepositorySessionInjector.injectRepositorySession(RepositorySessionInjector.java:22)
    at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:148)
    at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:107)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building NATS Parent POM 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (post-unit-test) @ nats-parent ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ nats-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ nats-parent >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ nats-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (post-unit-test) @ nats-parent ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ nats-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ nats-parent >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ nats-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ nats-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

**Comment by mcqueary** [comment]
I can't reproduce this using mvn package or mvn install. Seems like it's
not failing though.

On Monday, June 27, 2016, Remotegun.com notifications@github.com wrote:

> [INFO] Scanning for projects...
> 
> ## [INFO]
> 
> [INFO] Detecting the operating system and CPU architecture
> 
> ## [INFO]
> 
> [INFO] os.detected.name: osx
> [INFO] os.detected.arch: x86_64
> [INFO] os.detected.classifier: osx-x86_64
> [WARNING] Failed to inject repository session properties.
> java.lang.NoSuchMethodError:
> org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;
> at
> kr.motd.maven.os.RepositorySessionInjector.injectRepositorySession(RepositorySessionInjector.java:22)
> at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:148)
> at
> kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:107)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
> at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
> at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
> at java.lang.reflect.Method.invoke(Method.java:597)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
> [INFO]
> 
> ## [INFO]
> 
> [INFO] Building NATS Parent POM 1.0-SNAPSHOT
> 
> ## [INFO]
> 
> [INFO]
> [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @
> nats-parent ---
> [INFO]
> 
> ## [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent
> 
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (default-prepare-agent) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (pre-unit-test) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (post-unit-test)
> @ nats-parent ---
> [INFO] Skipping JaCoCo execution due to missing execution data
> file:/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
> [INFO]
> 
> ## [INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ nats-parent
> 
> [INFO] Not executing Javadoc as the project is not a Java
> classpath-capable package
> [INFO]
> [INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ nats-parent >>>
> [INFO]
> [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @
> nats-parent ---
> [INFO]
> 
> ## [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent
> 
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (default-prepare-agent) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (pre-unit-test) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
> [INFO]
> [INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ nats-parent <<<
> [INFO]
> [INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ nats-parent ---
> [INFO]
> [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @
> nats-parent ---
> [INFO]
> 
> ## [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent
> 
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (default-prepare-agent) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (pre-unit-test) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (post-unit-test)
> @ nats-parent ---
> [INFO] Skipping JaCoCo execution due to missing execution data
> file:/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
> [INFO]
> 
> ## [INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ nats-parent
> 
> [INFO] Not executing Javadoc as the project is not a Java
> classpath-capable package
> [INFO]
> [INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ nats-parent >>>
> [INFO]
> [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @
> nats-parent ---
> [INFO]
> 
> ## [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent
> 
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (default-prepare-agent) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent
> (pre-unit-test) @ nats-parent ---
> [INFO] surefireArgLine set to
> -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
> [INFO]
> [INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ nats-parent <<<
> [INFO]
> [INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ nats-parent ---
> 
> ## [INFO]
> 
> [INFO] BUILD SUCCESS
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nats-io/nats-parent-pom/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AGq4LFQQnO3EPphdVfTdohPeEmkWK-wbks5qP2dUgaJpZM4I-yBX
> .

## 

_Larry McQueary_ | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary

**Comment by FarzadAzima** [comment]
Are you using Mac?
