### ISSUE TITLE
Release Nats-parent?

### ISSUE THREAD

**Issue by oscerd** [nats-io/nats-parent-pom#3]
Do you plan to release NATS parent project on Maven Central? Or we need to use the SNAPSHOT repository?

I believe it would be better releasing the artifact on Central.

**Comment by oscerd** [comment]
Otherwise any project using Nats will need to add a snapshot repository to his configuration.

**Comment by Hronom** [comment]
+1 Fix dat

**Comment by mcqueary** [comment]
Resolved. The current stable release is `nats-parent-1.1`

**Comment by oscerd** [comment]
Thanks here too :-)

Il 29/ago/2016 20:50, "Larry McQueary" notifications@github.com ha
scritto:
